apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: hyperswitch-app-prod-app-set
  labels:
     app: hyperswitch-app-prod-set
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
  - list:
      elements:
      - cluster: local-as1
        url: https://kubernetes.default.svc
        helm_value: values.yaml
  template:
      metadata:
        name: 'hyperswitch-app-prod-app-{{cluster}}'
      spec:
        project: default
        source:
          path: charts/incubator/hyperswitch-app
          repoURL: 'https://github.com/juspay/hyperswitch-helm.git'
          targetRevision: HEAD
          helm:
            valueFiles:
              - '{{helm_value}}'
        destination:
          server: '{{url}}'
          namespace: hyperswitch-app-prod
        syncPolicy:
          syncOptions:
          - CreateNamespace=true
          automated:
            selfHeal: true
            prune: true