# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  package-hyperswitch-helm:
    #language=sh
    cmds:
      - >
        STACK=charts/hyperswitch-stack &&
        version=$(grep '^version:' $STACK/Chart.yaml | awk '{print $2}') &&
        helm package $STACK --dependency-update &&
        helm repo index $STACK --url https://juspay.github.io/hyperswitch-helm/v$version &&
        mkdir -p v$version && mv hyperswitch-stack-$version.tgz $STACK/index.yaml v$version &&
        helm repo index . --url https://juspay.github.io/hyperswitch-helm
    aliases:
      - phh

  update-readme:
    #language=sh
    cmds:
      - >
        docker run --rm
        -v $(pwd):/helm-docs
        -w /helm-docs
        jnorwood/helm-docs:latest
        --document-dependency-values=true
        --chart-search-root=charts
    aliases:
      - ur

  repo-update-index:
    #language=sh
    cmds:
      - >
        helm repo index repo
