# Test scenario 2: Global ingress enabled, but router ingress disabled
ingress:
  enabled: true

services:
  router:
    enabled: true
    ingress:
      enabled: false  # This should prevent router ingress creation
  controlCenter:
    enabled: true
    ingress:
      enabled: true