{{- if and .Values.services.router.enabled .Values.argoRollouts.enabled .Values.argoRollouts.canary.analysis.enabled }}
{{- include "hyperswitch.router.analysistemplate" (dict "root" . "key" "") }}
{{- end }}
