{{- if .Values.services.router.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: misc-cm-{{.Release.Name }}
data:
  # Configs from values.server.configs will be generated as environment variables with prefix ROUTER_
  {{- include "hyperswitch.configToEnvVars" (dict "config" .Values.server.configs "prefix" "ROUTER" "context" .) | nindent 2 }}
  # Additional Configs to override mounted production/sandbox/integration_test.toml configs
  {{- include "hyperswitch.configToEnvVars" (dict "config" .Values.server.additional_configs "prefix" "ROUTER" "context" .) | nindent 2 }}
{{- end }}
