{{- if .Values.services.consumer.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hyperswitch.producer.fullname" . }}-secret
data:
  ROUTER__FILE_UPLOAD_CONFIG__BUCKET_NAME: {{ "bucket" | b64enc }}
  ROUTER__FILE_UPLOAD_CONFIG__REGION: {{ "us-east-1"  | b64enc }}
  ROUTER__ANALYTICS__SQLX__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__HOST: {{ include "postgresqlreplica.host" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__PORT: {{ include "postgresqlreplica.port" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__MASTER_DATABASE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__MASTER_DATABASE__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__MASTER_DATABASE__PORT: {{ include "postgresql.port" . | toString | b64enc }}
  ROUTER__MASTER_DATABASE__USERNAME: {{ include "postgresql.username" . | b64enc }}
  ROUTER__REPLICA_DATABASE__HOST: {{ include "postgresql.host" . | b64enc }}
  ROUTER__REPLICA_DATABASE__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__REPLICA_DATABASE__PORT: {{ include "postgresql.port" . | toString | b64enc }}
  ROUTER__REPLICA_DATABASE__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__REDIS__HOST: {{ include "redis.host" .  | b64enc }}
  ROUTER__REDIS__PORT: {{ include "redis.port" . | toString | b64enc }}
  ROUTER__SECRETS__MIGRATION_ENCRYPTION_TIMESTAMP: {{ "1685510751" | b64enc }}
  ROUTER__LOCKER__REDIS_TEMP_LOCKER_ENCRYPTION_KEY: {{ .Values.server.secrets.redis_temp_locker_encryption_key | b64enc }}
{{- end }}
