apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sdk.fullname" . }}-nginx
  labels:
    {{- include "sdk.labels" . | nindent 4 }}
data:
  envBackendUrl: "{{ .Values.autoBuild.buildParam.envBackendUrl }}"
  envSdkUrl: "{{ .Values.autoBuild.buildParam.envSdkUrl }}"
  envLogsUrl: "{{ .Values.autoBuild.buildParam.envLogsUrl }}"
  disableCSP: "{{ .Values.autoBuild.buildParam.disableCSP}}"
  apiUrl: "{{ .Values.autoBuild.buildParam.appCloudFrontUrl }}"
  sdkUrl: "{{ .Values.autoBuild.buildParam.sdkCloudFrontUrl }}"
  default.conf: |-
    server {
        listen       {{ .Values.service.port }};
        listen  [::]:{{ .Values.service.port }};
        server_name  localhost;

        #access_log  /var/log/nginx/host.access.log  main;

        location {{ include "nginx.sdk.path" . }} {
            autoindex on;
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        location /HyperLoader.js {
              alias /usr/share/nginx/html{{ include "nginx.sdk.path" . }}/HyperLoader.js;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }

