{
 "title": "Payments Success Rate Monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "merchant_id",
    "label": "merchant_id",
    "query": "select distinct(merchant_id) from payment_intent"
   },
   {
    "name": "connector",
    "label": "connector",
    "query": "select connector from payment_attempt where connector != ''"
   },
   {
    "name": "payment_method_type",
    "label": "Payment Method Type",
    "query": "SELECT \n    CASE \n        WHEN payment_method_type IS NULL \n             OR payment_method_type = 'credit' \n             OR payment_method_type = 'debit' \n        THEN 'card'\n        ELSE payment_method_type\n    END AS payment_method_type\nFROM payment_attempt;"
   }
  ]
 },
 "panels": [
  {
   "title": "Success Rate Trends",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    { "title": "Merchant ID", "type": "volkovlabs-variable-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 } },
    {
     "title": "Day Wise Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "SELECT \n    TO_CHAR(created_at, 'YYYY-MM-DD') AS created_date_string,\n    created_at::date AS created_date,\n    CASE WHEN SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END) > 0 THEN \n        (SUM(CASE WHEN status in ('succeeded', 'requires_capture') THEN 1 ELSE 0 END)::decimal / SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END)) * 100 \n    ELSE \n        0 \n    END AS confirmed_success_rate,\n    CASE WHEN COUNT(*) > 0 THEN \n        (SUM(CASE WHEN status in ('succeeded', 'requires_capture') THEN 1 ELSE 0 END)::decimal / COUNT(*)) * 100 \n    ELSE \n        0 \n    END AS overall_success_rate,\n    CASE WHEN SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END) > 0 THEN \n        (SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END)::decimal / SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END)) * 100 \n    ELSE \n        0 \n    END AS failure_rate\nFROM \n    payment_intent\nWHERE \n    merchant_id IN (${merchant_id:singlequote})\n    AND created_at >= $__timeFrom()\n   AND created_at < CURRENT_DATE::TIMESTAMP\nGROUP BY \ncreated_date_string,\n    created_date"
      }
     ]
    },
    {
     "title": "Weekly Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "SELECT \n    TO_CHAR(DATE_TRUNC('week', created_at), 'YYYY-\"W\"IW') AS week_label,\n    DATE_TRUNC('week', created_at) AS created_week,\n    CASE WHEN SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END) > 0 THEN \n        (SUM(CASE WHEN status in ('succeeded', 'requires_capture') THEN 1 ELSE 0 END)::decimal / SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END)) * 100 \n    ELSE \n        0 \n    END AS confirmed_success_rate,\n    CASE WHEN COUNT(*) > 0 THEN \n        (SUM(CASE WHEN status in ('succeeded', 'requires_capture') THEN 1 ELSE 0 END)::decimal / COUNT(*)) * 100 \n    ELSE \n        0 \n    END AS overall_success_rate,\n    CASE WHEN SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END) > 0 THEN \n        (SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END)::decimal / SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END)) * 100 \n    ELSE \n        0 \n    END AS failure_rate\nFROM \n    payment_intent\nWHERE \n    merchant_id IN (${merchant_id:singlequote})\n    AND created_at >= $__timeFrom()\n    AND created_at < CURRENT_DATE::TIMESTAMP\nGROUP BY \n    week_label,\n    created_week\nORDER BY \n    created_week;"
      }
     ]
    },
    {
     "title": "Monthly Success Rate",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 29 },
     "targets": [
      {
       "rawSql": "SELECT \n    TO_CHAR(created_at, 'Month YYYY') AS month_label,\n    DATE_TRUNC('month', created_at) AS created_month,\n    CASE WHEN SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END) > 0 THEN \n        (SUM(CASE WHEN status in ('succeeded', 'requires_capture') THEN 1 ELSE 0 END)::decimal / SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END)) * 100 \n    ELSE \n        0 \n    END AS confirmed_success_rate,\n    CASE WHEN COUNT(*) > 0 THEN \n        (SUM(CASE WHEN status in ('succeeded', 'requires_capture') THEN 1 ELSE 0 END)::decimal / COUNT(*)) * 100 \n    ELSE \n        0 \n    END AS overall_success_rate,\n    CASE WHEN SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END) > 0 THEN \n        (SUM(CASE WHEN status = 'failed' THEN 1 ELSE 0 END)::decimal / SUM(CASE WHEN status != 'requires_payment_method' THEN 1 ELSE 0 END)) * 100 \n    ELSE \n        0 \n    END AS failure_rate\nFROM \n    payment_intent\nWHERE \n    merchant_id IN (${merchant_id:singlequote})\n    AND created_at >= $__timeFrom()\n   AND created_at < CURRENT_DATE::TIMESTAMP\nGROUP BY \nmonth_label, created_month\nORDER BY created_month"
      }
     ]
    }
   ]
  },
  {
   "title": "Success Rate Analytics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    { "title": "Merchant ID", "type": "volkovlabs-variable-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 } },
    {
     "title": "Connector",
     "type": "volkovlabs-variable-panel",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "sql": {
        "columns": [
         {
          "parameters": [],
          "type": "function"
         }
        ],
        "groupBy": [
         { "property": { "type": "string" }, "type": "groupBy" }
        ],
        "limit": 50
       }
      }
     ]
    },
    { "title": "Payment Method Type", "type": "volkovlabs-variable-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 } },
    {
     "title": "Merchant - SR",
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n    pa.merchant_id AS merchant_id,\n    COUNT(DISTINCT pi.id) AS total_payments,\n    COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) AS successful_payments,\n    CASE\n        WHEN COUNT(DISTINCT pi.id) = 0 THEN 0.0  -- Handle division by zero\n        ELSE COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) * 100.0 / COUNT(DISTINCT pi.id)\n    END AS payment_success_rate\nFROM\n    payment_attempt AS pa\nLEFT JOIN\n    payment_intent AS pi\nON\n    pa.payment_id = pi.payment_id\nWHERE\n    pi.merchant_id IN (${merchant_id:singlequote})\n    AND (pa.payment_method_type IN (${payment_method_type:singlequote}) OR pa.payment_method IN (${payment_method_type:singlequote}))\n    AND pa.connector IN (${connector:singlequote})\n    AND pa.created_at >= $__timeFrom() \n    AND pa.created_at <= $__timeTo()\nGROUP BY\n    pa.merchant_id\nORDER BY\n    total_payments DESC;"
      }
     ]
    },
    {
     "title": "Connector - SR",
     "type": "table",
     "gridPos": { "h": 12, "w": 13, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n    pa.connector AS connector_id,\n    COUNT(DISTINCT pi.id) AS total_payments,\n    COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) AS successful_payments,\n    COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) * 100.0 / COUNT(DISTINCT pi.id) AS payment_success_rate\nFROM\n    payment_attempt AS pa\nLEFT JOIN\n    payment_intent AS pi\nON\n    pa.payment_id = pi.payment_id\nWHERE\n    pi.merchant_id IN (${merchant_id:singlequote})\n    AND (pa.payment_method_type IN (${payment_method_type:singlequote}) OR pa.payment_method IN (${payment_method_type:singlequote}))\n    AND pa.connector IN (${connector:singlequote})\n    AND pi.created_at >= $__timeFrom() \n    AND pi.created_at <= $__timeTo()\nGROUP BY\n    pa.connector\nORDER BY\n    total_payments DESC;\n"
      }
     ]
    },
    {
     "title": "Payment Method Type - SR",
     "type": "table",
     "gridPos": { "h": 12, "w": 11, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n    pa.payment_method_type AS payment_method_type,\n    COUNT(DISTINCT pi.id) AS total_payments,\n    COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) AS successful_payments,\n    CASE\n        WHEN COUNT(DISTINCT pi.id) = 0 THEN 0.0  -- Handle division by zero\n        ELSE COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) * 100.0 / COUNT(DISTINCT pi.id)\n    END AS payment_success_rate\nFROM\n    payment_attempt AS pa\nLEFT JOIN\n    payment_intent AS pi\nON\n    pa.payment_id = pi.payment_id\nWHERE\n    pi.merchant_id IN (${merchant_id:singlequote})\n    AND (pa.payment_method_type IN (${payment_method_type:singlequote}) OR pa.payment_method IN (${payment_method_type:singlequote}))\n    AND pa.connector IN (${connector:singlequote})\n    AND pa.created_at >= $__timeFrom() \n    AND pa.created_at <= $__timeTo()\nGROUP BY\n    pa.payment_method_type\nORDER BY\n    total_payments DESC;"
      }
     ]
    },
    {
     "title": "MID <> Connector <> PMT - SR",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT\n    pa.merchant_id AS merchant_id,\n    pa.connector AS connector_id,\n    pa.payment_method_type AS payment_method_type,\n    COUNT(DISTINCT pi.id) AS total_payments,\n    COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) AS successful_payments,\n    COUNT(DISTINCT CASE WHEN pi.status = 'succeeded' THEN pi.id END) * 100.0 / COUNT(DISTINCT pi.id) AS payment_success_rate\nFROM\n    payment_attempt AS pa\nLEFT JOIN\n    payment_intent AS pi\nON\n    pa.payment_id = pi.payment_id\nWHERE\n    pi.merchant_id IN (${merchant_id:singlequote})\n    AND (pa.payment_method_type IN (${payment_method_type:singlequote}) OR pa.payment_method IN (${payment_method_type:singlequote}))\n    AND pa.connector IN (${connector:singlequote})\n    AND pi.created_at >= $__timeFrom() \n    AND pi.created_at <= $__timeTo()\nGROUP BY\n    pa.merchant_id,\n    pa.connector,\n    pa.payment_method_type\nORDER BY\n    total_payments DESC;\n"
      }
     ]
    }
   ]
  },
  { "title": "Merchant Success Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  { "title": "Merchant ID", "type": "volkovlabs-variable-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Connector",
   "type": "volkovlabs-variable-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  { "title": "Payment Method Type", "type": "volkovlabs-variable-panel", "gridPos": { "h": 4, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Confirmed Payments Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A) *100", "type": "math" }
   ]
  },
  {
   "title": "Overall Payments Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A) *100", "type": "math" }
   ]
  },
  {
   "title": "Payments Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A) *100", "type": "math" }
   ]
  },
  {
   "title": "Non Terminal Payments Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A) *100", "type": "math" }
   ]
  },
  {
   "title": "Retried Payments Success Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A) *100", "type": "math" }
   ]
  },
  {
   "title": "Retried Payments Failure Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($B/$A) *100", "type": "math" }
   ]
  },
  {
   "title": "Total transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Txns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) from payment_intent\n  INNER JOIN payment_attempt ON payment_intent.active_attempt_id = payment_attempt.attempt_id\n  WHERE payment_intent.created_at >= $__timeFrom() \n  AND payment_intent.created_at <= $__timeTo() \n  AND payment_intent.merchant_id IN (${merchant_id:singlequote})\n  AND (\n    payment_intent.status = 'requires_payment_method'\n    OR (payment_intent.status != 'requires_payment_method' AND connector IN (${connector:singlequote}) AND (payment_method_type IN (${payment_method_type:singlequote}) OR payment_method IN (${payment_method_type:singlequote})))\n  )\n"
    }
   ]
  },
  {
   "title": "Successful Transactions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Txns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) from payment_intent\n  INNER JOIN payment_attempt ON payment_intent.active_attempt_id = payment_attempt.attempt_id\n  WHERE payment_intent.created_at >= $__timeFrom() \n  AND payment_intent.created_at <= $__timeTo() \n  AND payment_intent.status  = 'succeeded'\n  AND payment_intent.merchant_id IN (${merchant_id:singlequote})\n  AND (payment_method_type IN (${payment_method_type:singlequote}) OR payment_method IN (${payment_method_type:singlequote}))\n  AND connector IN (${connector:singlequote})\n  "
    }
   ]
  },
  {
   "title": "User Dropouts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "Txns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(1) from payment_intent\n  INNER JOIN payment_attempt ON payment_intent.active_attempt_id = payment_attempt.attempt_id\n  WHERE payment_intent.created_at >= $__timeFrom() \n  AND payment_intent.created_at <= $__timeTo() \n  AND payment_intent.status  = 'requires_payment_method'\n  AND payment_intent.merchant_id IN (${merchant_id:singlequote})"
    }
   ]
  },
  {
   "title": "Top Error codes and messages for Merchant <> Connector",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT connector as \"Connector\", error_code as \"Error code\", error_reason as \"Error reason\", COUNT(1) AS \"Txns\" from payment_attempt\n  WHERE created_at >= $__timeFrom() \n  AND created_at <= $__timeTo() \n  AND status = 'failure'\n  AND merchant_id IN (${merchant_id:singlequote})\n  AND connector IN (${connector:singlequote})\n  AND (payment_method_type IN (${payment_method_type:singlequote}) OR payment_method IN (${payment_method_type:singlequote}))\n  GROUP BY connector, status, error_code, error_reason\n  ORDER BY \"Txns\" DESC"
    }
   ]
  },
  {
   "title": "Non Terminal Payment Details excluding Dropouts",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT payment_intent.merchant_id as \"Merchant ID\", payment_attempt.connector as \"Connector\", payment_attempt.payment_method_type as \"Payment Method Type\", payment_attempt.payment_method as \"Payment Method\", payment_intent.status as \"Status\", COUNT(1) AS \"Txns\" from payment_intent\n  INNER JOIN payment_attempt ON payment_intent.active_attempt_id = payment_attempt.attempt_id\n  WHERE payment_intent.created_at >= $__timeFrom() \n  AND payment_intent.created_at <= $__timeTo() \n  AND payment_intent.merchant_id IN (${merchant_id:singlequote})\n  AND payment_intent.status NOT IN ('succeeded', 'failed', 'requires_payment_method', 'cancelled', 'requires_capture')\n   AND (\n    payment_intent.status = 'requires_payment_method'\n    OR (payment_intent.status != 'requires_payment_method' AND connector IN (${connector:singlequote}) AND (payment_method_type IN (${payment_method_type:singlequote}) OR payment_method IN (${payment_method_type:singlequote})))\n  )\n  GROUP BY payment_intent.merchant_id, payment_intent.status, payment_attempt.connector, payment_attempt.payment_method, payment_attempt.payment_method_type"
    }
   ]
  },
  {
   "title": "Payments Stuck in Pending State",
   "type": "table",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "rawSql": "SELECT payment_intent.merchant_id,payment_attempt.payment_id,payment_attempt.connector,payment_intent.status as intent_status,payment_attempt.status as attempt_status,payment_intent.created_at, payment_attempt.payment_method,payment_attempt.payment_method_type\nFROM payment_attempt\n\nINNER JOIN payment_intent\nON payment_attempt.payment_id=payment_intent.payment_id\n\nand payment_attempt.merchant_id NOT LIKE ('hyperswitch%') \nand payment_attempt.created_at >= $__timeFrom() AND payment_attempt.created_at <= $__timeTo() \nand payment_attempt.status IN ('pending')\nand payment_attempt.connector NOT IN ('trustpay')\nAND payment_attempt.merchant_id IN (${merchant_id:singlequote})\nAND payment_attempt.connector IN (${connector:singlequote})\nAND (payment_attempt.payment_method_type IN (${payment_method_type:singlequote}) OR payment_attempt.payment_method IN (${payment_method_type:singlequote}))\n\nGROUP BY payment_intent.merchant_id,payment_intent.status,payment_attempt.status,payment_attempt.payment_id,payment_attempt.connector,payment_intent.created_at,payment_attempt.payment_method,payment_attempt.payment_method_type\nORDER BY payment_attempt.status,payment_intent.created_at DESC"
    }
   ]
  }
 ]
}