[analytics]
source = "{{ .Values.server.analytics.source }}"
forex_enabled = {{.Values.server.analytics.forex_enabled}}

[analytics.sqlx]
pool_size = {{ .Values.server.analytics.sqlx.pool_size }}             # Number of connections to keep open
connection_timeout = {{ .Values.server.analytics.sqlx.connection_timeout }}    # Timeout for database connection in seconds
queue_strategy = "{{ .Values.server.analytics.sqlx.queue_strategy }}"   # Add the queue strategy used by the database bb8 client

[kv_config]
ttl = {{ .Values.server.kv_config.tls }}
soft_kill = {{ .Values.server.kv_config.soft_kill }}

[paze_decrypt_keys]
paze_private_key = "{{ .Values.server.paze_decrypt_keys.paze_private_key }}"                       # Base 64 Encoded Private Key File cakey.pem generated for Paze -> Command to create private key: openssl req -newkey rsa:2048 -x509 -keyout cakey.pem -out cacert.pem -days 365
paze_private_key_passphrase = "{{ .Values.server.paze_decrypt_keys.paze_private_key_passphrase }}" # PEM Passphrase used for generating Private Key File cakey.pem

[google_pay_decrypt_keys]
google_pay_root_signing_keys = "{{ .Values.server.google_pay_decrypt_keys.google_pay_root_signing_keys }}"

[applepay_merchant_configs]
applepay_endpoint = "https://apple-pay-gateway.apple.com/paymentservices/registerMerchant" # Apple pay gateway merchant endpoint

[connector_onboarding.paypal]
enabled = {{ .Values.server.connector_onboarding.paypal.enabled }} # boolean

[connector_request_reference_id_config]
merchant_ids_send_payment_id_as_connector_request_id = {{ .Values.server.connector_request_reference_id_config.merchant_ids_send_payment_id_as_connector_request_id }}

[cors]
max_age = {{ .Values.server.cors.max_age }}                            # Maximum time (in seconds) for which this CORS request may be cached.
allowed_methods = "{{ .Values.server.cors.allowed_methods }}" # List of methods that are allowed
wildcard_origin = {{ .Values.server.cors.wildcard_origin }}                 # If true, allows any origin to make requests

[email]
active_email_client = "{{ .Values.server.email.active_email_client }}"

[email.aws_ses]
email_role_arn = "{{ .Values.server.email.aws_ses.email_role_arn }}"
sts_role_session_name = "{{ .Values.server.email.aws_ses.sts_role_session_name }}"

[email.smtp]
connection = "{{ .Values.server.email.smtp.connection }}"
host = "{{ .Values.server.email.smtp.host }}"
port = "{{ .Values.server.email.smtp.port }}"
timeout = {{ .Values.server.email.smtp.timeout }}

[events]
source = "{{ .Values.server.events.source }}"

[events.kafka]
brokers = {{ .Values.server.events.kafka.brokers }}
intent_analytics_topic = "{{ .Values.server.events.kafka.intent_analytics_topic }}"      # Kafka topic to be used for PaymentIntent events
attempt_analytics_topic = "{{ .Values.server.events.kafka.attempt_analytics_topic }}"     # Kafka topic to be used for PaymentAttempt events
refund_analytics_topic = "{{ .Values.server.events.kafka.refund_analytics_topic }}"      # Kafka topic to be used for Refund events
api_logs_topic = "{{ .Values.server.events.kafka.api_logs_topic }}"              # Kafka topic to be used for incoming api events
connector_logs_topic = "{{ .Values.server.events.kafka.connector_logs_topic }}"        # Kafka topic to be used for connector api events
outgoing_webhook_logs_topic = "{{ .Values.server.events.kafka.outgoing_webhook_logs_topic }}" # Kafka topic to be used for outgoing webhook events
dispute_analytics_topic = "{{ .Values.server.events.kafka.dispute_analytics_topic }}"     # Kafka topic to be used for Dispute events
audit_events_topic = "{{ .Values.server.events.kafka.audit_events_topic }}"          # Kafka topic to be used for Payment Audit events
payout_analytics_topic = "{{ .Values.server.events.kafka.payout_analytics_topic }}"      # Kafka topic to be used for Payouts and PayoutAttempt events
consolidated_events_topic = "{{ .Values.server.events.kafka.consolidated_events_topic }}"      # Kafka topic to be used for Consolidated events
authentication_analytics_topic = "{{ .Values.server.events.kafka.authentication_analytics_topic }}" # Kafka topic to be used for Authentication events
fraud_check_analytics_topic = "{{ .Values.server.events.kafka.fraud_check_analytics_topic }}"    # Kafka topic to be used for Fraud Check events
routing_logs_topic = "{{ .Values.server.events.kafka.routing_logs_topic }}"

[forex_api]          
data_expiration_delay_in_seconds = {{ .Values.server.forex_api.data_expiration_delay_in_seconds }}
redis_lock_timeout_in_seconds = {{ .Values.server.forex_api.redis_lock_timeout_in_seconds }}
redis_ttl_in_seconds = {{ .Values.server.forex_api.redis_lock_timeout_in_seconds }}

[locker]
host = "{{ .Values.server.locker.host }}"
host_rs = "{{ .Values.server.locker.host_rs}}"
mock_locker = {{ .Values.server.locker.mock_locker }}
locker_signing_key_id = "{{ .Values.server.locker.locker_signing_key_id }}"
locker_enabled = {{ .Values.server.locker.locker_enabled }}
ttl_for_storage_in_secs = {{ .Values.server.locker.ttl_for_storage_in_secs }}

[log.console]
enabled = {{ .Values.server.log.console.enabled }}
level = "{{ .Values.server.log.console.level }}"
log_format = "{{ .Values.server.log.console.log_format }}"

[log.file]
enabled = {{ .Values.server.log.file.enabled }}
level = "{{ .Values.server.log.file.level }}"
log_format = "{{ .Values.server.log.file.log_format }}"

[log.telemetry]
traces_enabled = {{ .Values.server.log.telemetry.traces_enabled }}                                # boolean [true or false], whether traces are enabled
metrics_enabled = {{ .Values.server.log.telemetry.metrics_enabled }}                               # boolean [true or false], whether metrics are enabled
ignore_errors = {{ .Values.server.log.telemetry.ignore_errors }}                                 # boolean [true or false], whether to ignore errors during traces or metrics pipeline setup
sampling_rate = {{ .Values.server.log.telemetry.sampling_rate }}                                   # decimal rate between 0.0 - 1.0
otel_exporter_otlp_endpoint = {{ include "opentelemetry-collector.url" . | quote }} # endpoint to send metrics and traces to, can include port number
otel_exporter_otlp_timeout = {{ .Values.server.log.telemetry.otel_exporter_otlp_timeout }}                     # timeout (in milliseconds) for sending metrics and traces
use_xray_generator = {{ .Values.server.log.telemetry.use_xray_generator }}                            # Set this to true for AWS X-ray compatible traces
route_to_trace = {{ .Values.server.log.telemetry.route_to_trace }}
bg_metrics_collection_interval_in_secs = {{ .Values.server.log.telemetry.bg_metrics_collection_interval_in_secs }}           # Interval for collecting the metrics in background thread

[lock_settings]
delay_between_retries_in_milliseconds = {{ .Values.server.lock_settings.delay_between_retries_in_milliseconds }} # Delay between retries in milliseconds
redis_lock_expiry_seconds = {{ .Values.server.lock_settings.redis_lock_expiry_seconds }}             # Seconds before the redis lock expires

[merchant_id_auth]
merchant_id_auth_enabled = {{ .Values.server.merchant_id_auth.merchant_id_auth_enabled }}

[master_database]
pool_size = "{{ .Values.server.master_database.pool_size }}"
connection_timeout = {{ .Values.server.master_database.connection_timeout }}   
queue_strategy = "{{ .Values.server.master_database.queue_strategy }}"

[generic_link]
[generic_link.payment_method_collect]
sdk_url = {{ include "hyperswitchWeb.hyperloaderUrl" . | quote }}
expiry = 900

[generic_link.payment_method_collect.ui_config]
theme = "{{ .Values.server.generic_link.payment_method_collect.ui_config.theme }}"
logo = "{{ .Values.server.generic_link.payment_method_collect.ui_config.logo }}"
merchant_name = "{{ .Values.server.generic_link.payment_method_collect.ui_config.merchant_name }}"

[generic_link.payment_method_collect.enabled_payment_methods]
card = "{{ .Values.server.generic_link.payment_method_collect.enabled_payment_methods.card }}"
bank_transfer = "{{ .Values.server.generic_link.payment_method_collect.enabled_payment_methods.bank_transfer }}"
wallet = "{{ .Values.server.generic_link.payment_method_collect.enabled_payment_methods.wallet }}"

[generic_link.payout_link]
sdk_url = {{ include "hyperswitchWeb.hyperloaderUrl" . | quote }}
expiry = 900

[generic_link.payout_link.ui_config]
theme = "{{ .Values.server.generic_link.payout_link.ui_config.theme }}"
logo = "{{ .Values.server.generic_link.payout_link.ui_config.logo }}"
merchant_name = "{{ .Values.server.generic_link.payout_link.ui_config.merchant_name }}"

[generic_link.payout_link.enabled_payment_methods]
card = "{{ .Values.server.generic_link.payout_link.enabled_payment_methods.card }}"

[payment_link]
sdk_url = {{ include "hyperswitchWeb.hyperloaderUrl" . | quote }}

[payment_method_auth]
redis_expiry = {{ .Values.server.payment_method_auth.redis_expiry }}          # Redis expiry time in milliseconds

{{- if .Values.server.proxy.enabled }}
[proxy]
http_url = "{{ .Values.server.proxy.http_url }}"    
https_url = "{{ .Values.server.proxy.https_url }}"
bypass_proxy_hosts = {{ .Values.server.proxy.bypass_proxy_hosts }}
{{- end }}

[redis]
host = "{{ .Values.server.redis.host }}"
port = {{ .Values.server.redis.port }}
pool_size = {{ .Values.server.redis.pool_size }} # Number of connections to keep open
reconnect_max_attempts = {{ .Values.server.redis.reconnect_max_attempts }} # Maximum number of reconnection attempts to make before failing. Set to 0 to retry forever.
reconnect_delay = {{ .Values.server.redis.reconnect_delay }} # Delay between reconnection attempts, in milliseconds
default_ttl = {{ .Values.server.redis.default_ttl }} # Default TTL for entries, in seconds
default_hash_ttl = {{ .Values.server.redis.default_hash_ttl }} # Default TTL for hashes entries, in seconds
use_legacy_version = {{ .Values.server.redis.use_legacy_version }} # RESP protocol for fred crate (set this to true if using RESPv2 or redis version < 6)
stream_read_count = {{ .Values.server.redis.stream_read_count }} # Default number of entries to read from stream if not provided in stream read options
auto_pipeline = {{ .Values.server.redis.auto_pipeline }} # Whether or not the client should automatically pipeline commands across tasks when possible.
disable_auto_backpressure = {{ .Values.server.redis.disable_auto_backpressure }} # Whether or not to disable the automatic backpressure features when pipelining is enabled.
max_in_flight_commands = {{ .Values.server.redis.max_in_flight_commands }} # The maximum number of in-flight commands (per connection) before backpressure will be applied.
default_command_timeout = {{ .Values.server.redis.default_command_timeout }} # An optional timeout to apply to all commands. In seconds
unresponsive_timeout = {{ .Values.server.redis.unresponsive_timeout }} # An optional timeout for Unresponsive commands in seconds. This should be less than default_command_timeout.
max_feed_count = {{ .Values.server.redis.max_feed_count }} # The maximum number of frames that will be fed to a socket before flushing.
cluster_enabled = {{ .Values.server.redis.cluster_enabled }} # boolean
cluster_urls = {{ .Values.server.redis.cluster_urls }} # List of redis cluster urls

[replica_database]
pool_size = "{{ .Values.server.replica_database.pool_size }}"
connection_timeout = {{ .Values.server.replica_database.connection_timeout }}   # Timeout for database connection in seconds
queue_strategy = "{{ .Values.server.replica_database.queue_strategy }}"   # Add the queue strategy used by the database bb8 client

[opensearch]
host = "{{ .Values.server.opensearch.host }}"
enabled = {{ .Values.server.opensearch.enabled }}

[opensearch.auth]
auth = "{{ .Values.server.opensearch.auth.auth }}"
username = "{{ .Values.server.opensearch.auth.username }}"
password = "{{ .Values.server.opensearch.auth.password }}"
region = "{{ .Values.server.opensearch.auth.region }}"

[opensearch.indexes]
payment_attempts = "{{ .Values.server.opensearch.indexes.payment_attempts }}"
payment_intents = "{{ .Values.server.opensearch.indexes.payment_intents }}"
refunds = "{{ .Values.server.opensearch.indexes.refunds }}"
disputes = "{{ .Values.server.opensearch.indexes.disputes }}"
sessionizer_payment_attempts = "{{ .Values.server.opensearch.indexes.sessionizer_payment_attempts }}"
sessionizer_payment_intents = "{{ .Values.server.opensearch.indexes.sessionizer_payment_intents }}"
sessionizer_refunds = "{{ .Values.server.opensearch.indexes.sessionizer_refunds }}"
sessionizer_disputes = "{{ .Values.server.opensearch.indexes.sessionizer_disputes }}"

[report_download_config]
dispute_function = "{{ .Values.server.report_download_config.dispute_function }}" # Config to download dispute report
payment_function = "{{ .Values.server.report_download_config.payment_function }}" # Config to download payment report
refund_function = "{{ .Values.server.report_download_config.refund_function }}"   # Config to download refund report
region = "{{ .Values.server.report_download_config.region }}" 
authentication_function = "{{ .Values.server.report_download_config.authentication_function }}"   

[server]
port = {{ .Values.server.server.port }}
host = "{{ .Values.server.server.host }}"
request_body_limit = {{ .Values.server.server.request_body_limit }} # Post request body is limited to 16k
shutdown_timeout = {{ .Values.server.server.shutdown_timeout }}
workers = {{ .Values.server.server.workers }}

[crm]
crm_manager = "{{ .Values.server.crm.crm_manager }}"
 
[crm.hubspot_proxy]
form_id = "{{ .Values.server.crm.hubspot_proxy.form_id }}"     
request_url = "{{ .Values.server.crm.hubspot_proxy.request_url }}"

# Secrets manager client to be used
{{- toToml (dict "secrets_management" .Values.server.secrets_management) | nindent 0 }}

# Encryption manager client to be used
{{- toToml (dict "encryption_management" .Values.server.encryption_management) | nindent 0 }}


{{- toToml (dict "multitenancy" .Values.server.multitenancy) | nindent 0 }}

{{- toToml (dict "user" .Values.server.user) | nindent 0 }}

[cell_information]
id = "{{ .Values.server.cell_information.id }}" # Default CellID for Global Cell Information

[network_tokenization_service]
generate_token_url= "{{ .Values.server.network_tokenization_service.generate_token_url }}"
fetch_token_url= "{{ .Values.server.network_tokenization_service.fetch_token_url }}"
token_service_api_key= "{{ .Values.server.network_tokenization_service.token_service_api_key }}"
public_key= "{{ .Values.server.network_tokenization_service.public_key }}"
private_key= "{{ .Values.server.network_tokenization_service.private_key }}"
key_id= "{{ .Values.server.network_tokenization_service.key_id }}"                    
delete_token_url= "{{ .Values.server.network_tokenization_service.delete_token_url }}"          
check_token_status_url= "{{ .Values.server.network_tokenization_service.check_token_status_url }}"    
webhook_source_verification_key= "{{ .Values.server.network_tokenization_service.webhook_source_verification_key }}" 

[grpc_client.dynamic_routing_client] # Dynamic Routing Client Configuration
host = "{{ .Values.server.grpc_client.dynamic_routing_client.host }}" 
port = {{ .Values.server.grpc_client.dynamic_routing_client.port }}        
service = "{{ .Values.server.grpc_client.dynamic_routing_client.service }}" 

[theme.storage]
file_storage_backend = "{{ .Values.server.theme.storage.file_storage_backend }}" 

[theme.storage.aws_s3]
region = "{{ .Values.server.theme.storage.aws_s3.region }}" 
bucket_name = "{{ .Values.server.theme.storage.aws_s3.bucket_name }}"   

[theme.email_config]
entity_name = "{{ .Values.server.theme.email_config.entity_name }}"                      
entity_logo_url = "{{ .Values.server.theme.email_config.entity_name }}" 
foreground_color = "{{ .Values.server.theme.email_config.entity_name }}"                     
primary_color = "{{ .Values.server.theme.email_config.entity_name }}"                        
background_color = "{{ .Values.server.theme.email_config.entity_name }}"                     

[connectors.unified_authentication_service] 
base_url = "{{ .Values.server.connectors.unified_authentication_service.base_url }}" 

[connectors.hyperswitch_vault] 
base_url = "{{ .Values.server.connectors.hyperswitch_vault }}"

[clone_connector_allowlist]
merchant_ids = "{{ .Values.server.clone_connector_allowlist.merchant_ids }}"
connector_names = "{{ .Values.server.clone_connector_allowlist.connector_names }}"

[grpc_client.unified_connector_service]
host = {{ .Values.server.grpc_client.unified_connectors_client.host | quote }}
port = {{ .Values.server.grpc_client.unified_connectors_client.port }}
connection_timeout = {{ .Values.server.grpc_client.unified_connectors_client.connection_timeout }}

[chat]
enabled = false                                # Enable or disable chat features
hyperswitch_ai_host = "http://0.0.0.0:8000"    # Hyperswitch ai workflow host
