apiVersion: v2
name: hyperswitch-ucs
description: A Helm chart for Hyperswitch UCS Service
type: application
version: 0.1.10-ucs-2026-09-29-0
appVersion: "v0.5.0"
keywords:
  - ucs
  - service
  - grpc
