apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    grafana_datasource: "1"
data:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: PostgreSQL
        type: postgres
        access: proxy
        url: {{ include "postgresql.host" . }}:{{ include "postgresql.port" . }}
        user: {{ include "postgresql.username" . }}
        password: {{ .Values.postgresql.global.postgresql.auth.password }}
        database: {{ include "postgresql.database" . }}
        uid: postgres_uid
        jsonData:
          sslmode: "disable"
        secureJsonData:
          password: {{ .Values.postgresql.global.postgresql.auth.password }}
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-{{ .Values.prometheus.host }}:{{ .Values.prometheus.port }}
        isDefault: true
        uid: "my-prometheus"
        jsonData:
          timeInterval: "5s"
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ .Values.loki.host }}:{{ .Values.loki.port }}
        uid: "loki"



