apiVersion: v2
appVersion: 1.16.0
description: Hyperswitch is a community-led, open payments switch designed to empower digital businesses by providing fast, reliable, and affordable access to the best payments infrastructure.
name: hyperswitch-app
type: application
version: 0.2.4
dependencies:
  - name: redis
    version: 18.6.1
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.5.38
    condition: postgresql.enabled
  - name: hyperswitch-card-vault
    version: 0.1.0
    repository: "file://../hyperswitch-card-vault"
    condition: hyperswitch-card-vault.enabled
  - name: kafka
    version: 31.0.0
    repository: https://charts.bitnami.com/bitnami
    condition: kafka.enabled
  - name: clickhouse
    version: 6.3.3
    repository: https://charts.bitnami.com/bitnami
    condition: clickhouse.enabled
  - name: mailhog
    version: 4.0.0
    repository: https://codecentric.github.io/helm-charts
    condition: mailhog.enabled
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
    condition: loki.enabled
  - name: vector
    version: 0.37.0
    repository: https://helm.vector.dev
    condition: vector.enabled
  - name: opentelemetry-collector
    version: 0.120.0
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector.enabled
