apiVersion: v1
entries:
  hyperswitch-card-vault:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-12T19:16:42.430039+05:30"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.5.38
    description: A Helm chart for creating Hyperswitch Card Vault
    digest: 1a05802985fd9063e49ab587e4385495866f9c649680a9da5421af02f5272d07
    name: hyperswitch-card-vault
    type: application
    urls:
    - https://juspay.github.io/charts/incubator/hyperswitch-app/charts/hyperswitch-card-vault-0.1.0.tgz
    version: 0.1.0
  hyperswitch-app:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-02-12T19:16:42.425551+05:30"
    dependencies:
    - condition: redis.enabled
      name: redis
      repository: https://charts.bitnami.com/bitnami
      version: 18.6.1
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.5.38
    - condition: hyperswitch-card-vault.enabled
      name: hyperswitch-card-vault
      repository: file://../hyperswitch-card-vault
      version: 0.1.0
    - condition: hyperswitch-web.enabled
      name: hyperswitch-web
      repository: file://../hyperswitch-web
      version: 0.1.0
    description: Hyperswitch is a community-led, open payments switch designed to empower digital businesses by providing fast, reliable, and affordable access to the best payments infrastructure.
    digest: 322d5d28cbbd9073d9b6fc026cf32560be05155f6b1169f9eee179a72f6ff93b
    name: hyperswitch-app
    type: application
    urls:
    - https://juspay.github.io/charts/incubator/hyperswitch-app/hyperswitch-app-0.1.0.tgz
    version: 0.1.0
  hyperswitch-web:
  - apiVersion: v2
    appVersion: 0.15.8
    created: "2024-02-12T19:16:42.430653+05:30"
    description: 'Helm chart for Hyperswitch SDK static Server. This chart allow end
      user to deploy standalone  [SDK](https://github.com/juspay/hyperswitch-web)
      with different way:   - prebuilt nginx static server (deployment - required
      a specific docker build)    - autobuild nginx static server (statefulset and
      assets saved in PVC)   The prebuilt image is suitable for production, no building
      time. Autobuild is suitable to quick start, assets are built in initContainer
      and saved in PVC. Nginx container will serve  assets'
    digest: b65cc1aff20bbd241de410bfc65bd74b4b2bce00d22d0e0ccefb77bd9a01dbc8
    name: hyperswitch-web
    type: application
    urls:
    - https://juspay.github.io/charts/incubator/hyperswitch-app/charts/hyperswitch-web-0.1.0.tgz
    version: 0.1.0
  postgresql:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r93
        - name: postgres-exporter
          image: docker.io/bitnami/postgres-exporter:0.15.0-debian-11-r4
        - name: postgresql
          image: docker.io/bitnami/postgresql:16.1.0-debian-11-r18
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 16.1.0
    created: "2024-02-12T19:16:42.433585+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: PostgreSQL (Postgres) is an open source object-relational database
      known for reliability and data integrity. ACID-compliant, it supports foreign
      keys, joins, views, triggers and stored procedures.
    digest: 9e3ab42d8197aac72722a3557d1f8ed04adc0fd5768e1985569bc73eaddc3b9c
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/postgresql/img/postgresql-stack-220x234.png
    keywords:
    - postgresql
    - postgres
    - database
    - sql
    - replication
    - cluster
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: postgresql
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/postgresql
    urls:
    - https://juspay.github.io/charts/incubator/hyperswitch-app/charts/postgresql-15.5.38.tgz
    version: 15.5.38
  redis:
  - annotations:
      category: Database
      images: |
        - name: os-shell
          image: docker.io/bitnami/os-shell:11-debian-11-r92
        - name: redis-exporter
          image: docker.io/bitnami/redis-exporter:1.55.0-debian-11-r3
        - name: redis-sentinel
          image: docker.io/bitnami/redis-sentinel:7.2.3-debian-11-r2
        - name: redis
          image: docker.io/bitnami/redis:7.2.3-debian-11-r2
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 7.2.3
    created: "2024-02-12T19:16:42.438619+05:30"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: Redis(R) is an open source, advanced key-value store. It is often
      referred to as a data structure server since keys can contain strings, hashes,
      lists, sets and sorted sets.
    digest: 7069129ea36d50ec9c6b494aa4d7e85395f443e36c4ba8765506776dcae03f3a
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
    keywords:
    - redis
    - keyvalue
    - database
    maintainers:
    - name: VMware, Inc.
      url: https://github.com/bitnami/charts
    name: redis
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/redis
    urls:
    - https://juspay.github.io/charts/incubator/hyperswitch-app/charts/redis-18.6.1.tgz
    version: 18.6.1
generated: "2024-02-12T19:16:42.411118+05:30"
