# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  check-helm-docs:
    desc: "Check if helm-docs is installed"
    #language=sh
    cmds:
      - >
        command -v helm-docs &> /dev/null || 
        (echo "helm-docs is not installed. Please install it from https://github.com/norwoodj/helm-docs/releases"; exit 1)
    silent: true

  install-pg-ext:
    desc: install bitnami postgres external
    cmds:
      - >-
        helm install postgresql-ext bitnami/postgresql 
        --version 15.5.38 
        -f dev/bitnami-pg.values.yaml 
        -n hyperswitch 
        --debug
    aliases:
      - ipe

  template:
    cmds:
      - helm template test  . -f values.yaml --debug > render.yaml
    aliases:
      - t

  install:
    cmds:
      - helm upgrade --install hyperswitch-v1  . -f values.yaml -n hyperswitch --debug
    aliases:
      - i

  dry-run:
    desc: dry run chart installation
    cmds:
      - helm upgrade --install hyperswitch-v1  . -f values.yaml -n hyperswitch --debug --dry-run
    aliases:
      - dr

  generate-doc:
    cmds:
      - task: check-helm-docs
      - helm-docs
    aliases:
      - d

  helm-add-repo:
    desc: helm add repo and upgrade
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm repo update
    aliases:
      - har

  helm-redis-install:
    desc: deploy standalone bitnami redis based on helm chart
    cmds:
      - task: helm-add-repo
      - >-
        helm upgrade 
        --install 
        {{ .RELEASE_NAME }} 
        bitnami/redis 
        --version 18.6.1 
        -n {{ .NAMESPACE }} 
        --debug  
        -f dev/bitnami-redis-values.yaml
    vars:
      RELEASE_NAME: redis-ext
      NAMESPACE: hyperswitch
    aliases:
      - hri

  helm-postgres-install:
    desc:  deploy standalone Postgresql based on helm chart
    cmds:
      - task: helm-add-repo
      - >- 
        helm upgrade
        --install 
        {{ .RELEASE_NAME }} 
        bitnami/postgresql 
        --version 15.5.38 
        -n {{ .NAMESPACE }} 
        --debug
        -f dev/bitnami-pg.values.yaml
    vars:
      RELEASE_NAME: postgresql-ext
      NAMESPACE: hyperswitch
    aliases:
      - hpi
