{{- if .Values.externalRedis.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "externalRedis.secret.name" . }}
data:
  host: {{ .Values.externalRedis.host  | quote | b64enc }}
  port: {{ .Values.externalRedis.port  | quote | b64enc }}
  {{- if .Values.externalRedis.auth.enabled }}
  username: {{ .Values.externalRedis.auth.username | quote | b64enc }}
  password: {{ .Values.externalRedis.auth.password  | quote | b64enc }}
  {{ end }}
{{- end }}
