apiVersion: v1
data:
  BACH__KEYS__TEMP_CARD_KEY: 
  BACH_READ_USER_PWD: 
  ROUTER__ANALYTICS__SQLX__DBNAME: 
  ROUTER__ANALYTICS__SQLX__KMS_ENCRYPTED_PASSWORD: 
  ROUTER__ANALYTICS__SQLX__USERNAME: 
  ROUTER__API_KEYS__KMS_ENCRYPTED_HASH_KEY: 
  ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY1: 
  ROUTER__JWEKEY__LOCKER_DECRYPTION_KEY2: 
  ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY1: 
  ROUTER__JWEKEY__LOCKER_ENCRYPTION_KEY2: 
  ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER1: 
  ROUTER__JWEKEY__LOCKER_KEY_IDENTIFIER2: 
  ROUTER__JWEKEY__TUNNEL_PRIVATE_KEY: 
  ROUTER__JWEKEY__VAULT_ENCRYPTION_KEY: 
  ROUTER__JWEKEY__VAULT_PRIVATE_KEY: 
  ROUTER__KMS__KEY_ID: 
  ROUTER__KMS__REGION: 
  ROUTER__LOCKER__BASILISK_HOST: 
  ROUTER__SECRETS__KMS_ENCRYPTED_ADMIN_API_KEY: 
  ROUTER__SECRETS__KMS_ENCRYPTED_JWT_SECRET: 
  ROUTER__SECRETS__MASTER_ENC_KEY: 
kind: Secret
metadata:
  name: hyperswitch-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
