apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: hyperswitch-control-center-destinations
  namespace: hyperswitch
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  exportTo:
  - '*'
  host: hyperswitch-control-center
  subsets:
  - labels:
      version: {{ .Values.hyperswitchControlCenter.version }}
    name: {{ .Values.hyperswitchControlCenter.version }}
  trafficPolicy:
    loadBalancer:
      simple: LEAST_CONN
