{{- if .Values.autoscaling.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hyperswitch-server-v1o113o0
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hyperswitch-server-v1o113o0
  minReplicas: 3
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
{{- end }}
