apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperswitch-card-vault-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  {{- with (default .Values.global.annotations .Values.server.annotations) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hyperswitch-card-vault
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- with (default .Values.global.annotations .Values.server.pod.annotations) }}
        {{- toYaml . | nindent 8 }} 
        {{- end }}
      labels:
        app: hyperswitch-card-vault
    spec:
      {{- with (default .Values.global.tolerations .Values.server.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.affinity .Values.server.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.nodeSelector .Values.server.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      containers:
        - env:
            - name: LOCKER__LOG__CONSOLE__ENABLED
              value: "true"
            - name: LOCKER__LOG__CONSOLE__LEVEL
              value: DEBUG
            - name: LOCKER__LOG__CONSOLE__LOG_FORMAT
              value: default
            - name: LOCKER__SERVER__HOST
              value: {{ include "locker.server.host" . }}
            - name: LOCKER__SERVER__PORT
              value: {{ include "locker.server.port" . }}
            - name: LOCKER__DATABASE__USERNAME
              value: {{ include "locker-psql.username" . }}
            - name: LOCKER__DATABASE__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__DATABASE__PASSWORD
            - name: LOCKER__DATABASE__HOST
              value: {{ include "locker-psql.host" . }}
            - name: LOCKER__DATABASE__PORT
              value: {{ include "locker-psql.port" . }}
            - name: LOCKER__DATABASE__DBNAME
              value: {{ include "locker-psql.name" . }}
            - name: LOCKER__LIMIT__REQUEST_COUNT
              value: "100"
            - name: LOCKER__LIMIT__DURATION
              value: "60"
            - name: LOCKER__SECRETS__TENANT
              value: hyperswitch
            - name: LOCKER__SECRETS__LOCKER_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__SECRETS__LOCKER_PRIVATE_KEY
            - name: LOCKER__TENANT_SECRETS__PUBLIC__MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__TENANT_SECRETS__PUBLIC__MASTER_KEY
            - name: LOCKER__TENANT_SECRETS__PUBLIC__PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__TENANT_SECRETS__PUBLIC__PUBLIC_KEY
            - name: LOCKER__TENANT_SECRETS__PUBLIC__SCHEMA
              value: {{ .Values.tenant_secrets.public.schema | quote }}
            {{- if eq .Values.backend "aws" }}
            - name: LOCKER__SECRETS_MANAGEMENT__SECRETS_MANAGER
              value: "aws_kms"
            - name: LOCKER__SECRETS_MANAGEMENT__AWS_KMS__KEY_ID
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__SECRETS_MANAGEMENT__AWS_KMS__KEY_ID
            - name: LOCKER__SECRETS_MANAGEMENT__AWS_KMS__REGION
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__SECRETS_MANAGEMENT__AWS_KMS__REGION
            {{- else if eq .Values.backend "vault" }}
            - name: LOCKER__SECRETS_MANAGEMENT__SECRETS_MANAGER
              value: "hashi_corp_vault"
            - name: LOCKER__SECRETS_MANAGEMENT__HASHI_CORP_VAULT__URL
              value: {{ .Values.server.vault.url | quote }}
            - name: LOCKER__SECRETS_MANAGEMENT__HASHI_CORP_VAULT__TOKEN
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__SECRETS_MANAGEMENT__HASHI_CORP_VAULT__TOKEN
            {{- end }}
            - name: LOCKER__CACHE__MAX_CAPACITY
              value: "5000"
            - name: LOCKER__CACHE__TTI
              value: "7200"
            - name: LOCKER__EXTERNAL_KEY_MANAGER__URL
              value: {{ .Values.server.externalKeyManager.url | quote }}
            {{- if .Values.secrets.external_key_manager.cert }}
            - name: LOCKER__EXTERNAL_KEY_MANAGER__CERT
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__EXTERNAL_KEY_MANAGER__CERT
            {{- end }}
            {{- if .Values.secrets.api_client.identity }}
            - name: LOCKER__API_CLIENT__IDENTITY
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__API_CLIENT__IDENTITY
            {{- end }}
            {{- if .Values.secrets.tls.certificate }}
            - name: LOCKER__TLS__CERTIFICATE
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__TLS__CERTIFICATE
            {{- end }}
            {{- if .Values.secrets.tls.private_key }}
            - name: LOCKER__TLS__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__TLS__PRIVATE_KEY
            {{- end }}
            {{- if .Values.server.extra.env }}
            {{- range $key, $value := .Values.server.extra.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
          image: {{ .Values.server.image }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/bash
                  - -c
                  - pkill -15 node
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          name: tartarus
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 50
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi

          securityContext:
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /local/config/development.toml
              name: hyperswitch-vault-config
              subPath: development.toml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: hyperswitch-vault-role
      serviceAccountName: hyperswitch-vault-role
      terminationGracePeriodSeconds: 120
      volumes:
        - configMap:
            defaultMode: 420
            name: hyperswitch-vault-config-{{ .Release.Name }}
          name: hyperswitch-vault-config
