{{- if .Values.initDB.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: hyperswitch-create-locker-db-{{ regexReplaceAll "\\." .Values.server.version "-" }}
  labels:
    app: hyperswitch-create-locker-db-{{ regexReplaceAll "\\." .Values.server.version "-" }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure

      {{- with (default .Values.global.tolerations .Values.server.pod.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.affinity .Values.server.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (default .Values.global.nodeSelector .Values.server.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      initContainers:
        {{- include "locker-psql.initContainer.check.ready" . | nindent 8 }}

      containers:
        - name: run-locker-db-migration
          image: {{ .Values.initDB.migration.image }}
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |-
              echo "Downloading migrations..."
              curl -L -o hyperswitch-card-vault.tar.gz https://github.com/juspay/hyperswitch-card-vault/archive/refs/tags/$VERSION.tar.gz
              tar -xzvf hyperswitch-card-vault.tar.gz --transform 's|[^/]*/|hyperswitch-card-vault/|'
              cd hyperswitch-card-vault
              
              echo "Running Diesel migrations"
              diesel migration run \
                --database-url postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:$POSTGRES_PORT/$DBNAME

              echo "Completed Card-Vault database migration"
          env:
            - name: POSTGRES_HOST
              value: {{ include "locker-psql.host" . }}
            - name: POSTGRES_PORT
              value: {{ include "locker-psql.port" . }}
            - name: DBNAME
              value: {{ include "locker-psql.name" . }}
            - name: POSTGRES_USER
              value: {{ include "locker-psql.username" . }}
            - name: VERSION
              value: {{ .Values.server.version }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: locker-secrets-{{ .Release.Name }}
                  key: LOCKER__DATABASE__PASSWORD
{{- end }}