apiVersion: v1
data:
  LOCKER__DATABASE__PASSWORD: {{ include "locker-psql.password" . | b64enc }}
  LOCKER__SECRETS__LOCKER_PRIVATE_KEY: {{ .Values.server.secrets.locker_private_key | b64enc }}
  LOCKER__TENANT_SECRETS__PUBLIC__MASTER_KEY: {{ .Values.server.tenant_secrets.public.master_key | b64enc }}
  LOCKER__TENANT_SECRETS__PUBLIC__PUBLIC_KEY: {{ .Values.server.tenant_secrets.public.public_key | b64enc }}
  LOCKER__TENANT_SECRETS__PUBLIC__SCHEMA: {{ .Values.server.tenant_secrets.public.schema | b64enc }}
kind: Secret
metadata:
  name: locker-secrets-{{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
