apiVersion: v1
data:
  LOCKER__DATABASE__PASSWORD: {{ include "locker-psql.password" . | b64enc }}
  LOCKER__SECRETS__LOCKER_PRIVATE_KEY: {{ .Values.secrets.locker_private_key | b64enc }}
  LOCKER__TENANT_SECRETS__PUBLIC__MASTER_KEY: {{ .Values.tenant_secrets.public.master_key | b64enc }}
  LOCKER__TENANT_SECRETS__PUBLIC__PUBLIC_KEY: {{ .Values.tenant_secrets.public.public_key | b64enc }}
  
  {{- if eq .Values.backend "aws" }}
  LOCKER__SECRETS_MANAGEMENT__AWS_KMS__KEY_ID: {{ .Values.secrets.aws.key_id | b64enc }}
  LOCKER__SECRETS_MANAGEMENT__AWS_KMS__REGION: {{ .Values.secrets.aws.region | b64enc }}
  {{- else if eq .Values.backend "vault" }}
  LOCKER__SECRETS_MANAGEMENT__HASHI_CORP_VAULT__TOKEN: {{ .Values.secrets.vault.token | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.tls.certificate }}
  LOCKER__TLS__CERTIFICATE: {{ .Values.secrets.tls.certificate | b64enc }}
  {{- end }}
  {{- if .Values.secrets.tls.private_key }}
  LOCKER__TLS__PRIVATE_KEY: {{ .Values.secrets.tls.private_key | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.external_key_manager.cert }}
  LOCKER__EXTERNAL_KEY_MANAGER__CERT: {{ .Values.secrets.external_key_manager.cert | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.api_client.identity }}
  LOCKER__API_CLIENT__IDENTITY: {{ .Values.secrets.api_client.identity | b64enc }}
  {{- end }}
kind: Secret
metadata:
  name: {{ include "hyperswitch-card-vault.secrets.name" . }}
  namespace: {{ .Release.Namespace }}
type: Opaque
