apiVersion: v1
kind: Service
metadata:
  name: {{ include "hyperswitch-card-vault.service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8080
  selector:
    app: hyperswitch-card-vault
  sessionAffinity: None
  type: ClusterIP
