{{- if .Values.services.consumer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-cm-{{ .Release.Name }}
data:
  # Configs from values.consumer.configs will be generated as environment variables with prefix ROUTER_
  {{- include "hyperswitch.configToEnvVars" (dict "config" .Values.consumer.configs "prefix" "ROUTER" "context" .) | nindent 2 }}
{{- end }}
