{{- if .Values.services.consumer.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: consumer-cm-{{ .Release.Name }}
data:
  consumer.toml: |
    {{ .Files.Get "configs/consumer.toml" | nindent 4 }}
    {{- if eq .Values.server.run_env "production" -}}
    {{ .Files.Get "configs/router-production.toml" | nindent 4 }}
    {{- else if eq .Values.server.run_env "sandbox" -}}
    {{ .Files.Get "configs/router-sandbox.toml" | nindent 4 }}
    {{- else -}}
    {{ .Files.Get "configs/router-integ.toml" | nindent 4 }}
    {{- end }}
{{- end }}
