apiVersion: v2
name: hyperswitch-external-secrets
description: External Secrets Operator integration for Hyperswitch applications
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - hyperswitch
  - external-secrets
  - secrets-management
  - kubernetes
dependencies: []





