# Integration Example: Using hyperswitch-external-secrets with hyperswitch-app
# ================================================================================
# This file shows how to configure hyperswitch-app chart to use external secrets
# created by the hyperswitch-external-secrets chart instead of hardcoded values.

# Step 1: Deploy hyperswitch-external-secrets chart
# helm install eso-secrets ./charts/incubator/hyperswitch-external-secrets

# Step 2: Use this example configuration in your hyperswitch-app values.yaml
# to replace _secret patterns with _secretRef patterns:

server:
  configs:
    # Analytics configuration
    analytics:
      clickhouse:
        password:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__ANALYTICS__CLICKHOUSE__PASSWORD
      sqlx:
        password:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__ANALYTICS__SQLX__PASSWORD

    # Apple Pay configuration
    applepay_merchant_configs:
      merchant_cert:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_MERCHANT_CONFIGS__MERCHANT_CERT
      merchant_cert_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_MERCHANT_CONFIGS__MERCHANT_CERT_KEY
      common_merchant_identifier:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_MERCHANT_CONFIGS__COMMON_MERCHANT_IDENTIFIER

    applepay_decrypt_keys:
      apple_pay_merchant_cert:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_MERCHANT_CERT
      apple_pay_merchant_cert_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_MERCHANT_CERT_KEY
      apple_pay_ppc:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_PPC
      apple_pay_ppc_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_PPC_KEY

    # Connector onboarding
    connector_onboarding:
      paypal:
        client_id:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_ID
        client_secret:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_SECRET
        partner_id:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__CONNECTOR_ONBOARDING__PAYPAL__PARTNER_ID

    # Email configuration
    email:
      smtp:
        username:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__EMAIL__SMTP__USERNAME
        password:
          _secretRef:
            name: hyperswitch-secrets
            key: ROUTER__EMAIL__SMTP__PASSWORD

    # Forex API
    forex_api:
      api_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__FOREX_API__API_KEY
      fallback_api_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__FOREX_API__FALLBACK_API_KEY

    # Locker configuration
    locker:
      redis_temp_locker_encryption_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__LOCKER__REDIS_TEMP_LOCKER_ENCRYPTION_KEY

    # Payment method authentication
    payment_method_auth:
      pm_auth_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__PAYMENT_METHOD_AUTH__PM_AUTH_KEY

    # KMS configuration
    kms:
      key_id:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__KMS__KEY_ID

    # JWE Keys
    jwekey:
      vault_encryption_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__JWEKEY__VAULT_ENCRYPTION_KEY
      vault_private_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__JWEKEY__VAULT_PRIVATE_KEY
      tunnel_private_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__JWEKEY__TUNNEL_PRIVATE_KEY
      rust_locker_encryption_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__JWEKEY__RUST_LOCKER_ENCRYPTION_KEY

    # API Keys
    api_keys:
      hash_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__API_KEYS__HASH_KEY

    # Key Manager
    key_manager:
      ca:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__KEY_MANAGER__CA
      cert:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__KEY_MANAGER__CERT

    # User authentication
    user_auth_methods:
      encryption_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__USER_AUTH_METHODS__ENCRYPTION_KEY

    # Application secrets
    secrets:
      admin_api_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__SECRETS__ADMIN_API_KEY
      jwt_secret:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__SECRETS__JWT_SECRET
      master_enc_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__SECRETS__MASTER_ENC_KEY
      recon_admin_api_key:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__SECRETS__RECON_ADMIN_API_KEY
      migration_encryption_timestamp:
        _secretRef:
          name: hyperswitch-secrets
          key: ROUTER__SECRETS__MIGRATION_ENCRYPTION_TIMESTAMP

# Step 3: Deploy hyperswitch-app with the external secrets configuration
# helm upgrade --install hyperswitch ./charts/incubator/hyperswitch-app -f values-with-external-secrets.yaml