{{- $eso := .Values.externalSecretsOperator }}
{{- if and $eso.enabled $eso.serviceAccount.create }}
{{- $serviceAccountName := $eso.serviceAccount.name | default "hyperswitch-ucs-eso-sa" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperswitch-ucs.labels" . | nindent 4 }}
    {{- with $eso.serviceAccount.extraLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with $eso.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
